---
title: ""
author: "Igo da Costa Andrade"

# Metadados
booktitle: "Cálculo"
booksubtitle: "Volume I"
bookauthors: "Apostol, T. M."
bookaddres: "México"
bookpublisher: "Editorial Reverté"
bookyear: "2001"
maincolor: "b8004a"
chaptertitle: "Introdução"
chapternumber: "I"

output: 
  bookdown::pdf_document2:
    template: template.tex
knit: >-
  (function(inputFile, encoding) {
    rmarkdown::render(
      input = inputFile,
      encoding = encoding,
      output_dir = file.path(dirname(inputFile), "../output"),
      output_format = "bookdown::pdf_document2"
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
use_python("~/anaconda3/envs/science/bin/python")
```

\section*{I 1.4 Exercícios - p. 9}

\begin{enumerate}
  \item 
  \begin{enumerate}[label=(\alph*)]
    \item Modificar a região na figura I.3 tomando como ordenada para cada $x$ o valor $2x^2$ em vez de $x^2$. Desenhar a nova figura. Seguindo neste caso os passos principais de desenvolvimento anterior e comparando ambos, estudando a repercussão da mudança no cálculo de $A$. 
  \end{enumerate}
  \iniSol
  \begin{enumerate}[label=(\alph*)]
    \item 
    \begin{figure}[H]
    \centering
    \caption{Cálculo da área do segmento parabólico mediante aproximação por falta e por excesso} \label{fig:seg-parabolico-a}
    \vspace{0.5cm}
    \begin{tikzpicture}[x=1.5cm, y=0.75cm]
    \begin{scope}
      \draw[mainColor, thick, domain=0:2, samples=50] plot (\x, {2*(\x)^2});
      \draw[thick] (-0.5, 0) -- (0, 0) node[below] {$0$} -- (2.5, 0);
      \draw[dashed] (0,0) -- (0, 8) -- (2, 8);
      \draw (1, 2) -- (1, 0) node[below] {$x$} node[midway, right] {$2x^2$};
      \draw (2, 8) -- (2, 0) node[below] {$b$} node[midway, right] {$2b^2$};
      \node at (1, -1.5) {(a) $y = 2x^2$};
    \end{scope}
    \begin{scope}[xshift=5cm]
      \draw[mainColor, thick, domain=0:2, samples=50] plot (\x, {2*(\x)^2});
      \draw[thick] (-0.5, 0) -- (0,0) node[below] {$0$} -- (2.5, 0);
      \draw[dashed] (0,0) -- (0, 8) -- (2, 8);
      \draw (2, 8) -- (2, 0);
      \foreach \x in {0, 0.4, 1.2} {
        \draw[fill=mainColor!20] (\x, 0) rectangle ({\x+0.4}, {2*\x^2});
      }
      \node[below] at (0.4, 0) {$\frac{b}{n}$};
      \node[below] at (0.8, 0) {$\frac{2b}{n}$};
      \node[below] at (1.2, 0) {$\frac{kb}{n}$};
      \node[below right] at (2.0, 0) {$b = \frac{nb}{n}$};
      \draw[<->] (1.2, 3.) -- ++(0.4, 0) node[midway, above] {$\frac{b}{n}$};
      \draw[<->] (1.7, 0) -- ++(0, 2.88) node[midway, right, fill=white, xshift=0.1cm] {$2\left(\frac{kb}{n}\right)^2$};
      \draw[-latex] (0.8, 3.6) node[above] {\small $A_k = 2 \dfrac{b^3}{n^3} k^2$} -- (1.2, 2.88); 
      \node at (1, -1.5) {(b) Por falta};
    \end{scope}
    \begin{scope}[xshift=10cm]
      \draw[thick] (-0.5, 0) -- (0,0) node[below] {$0$} -- (2.5, 0);
      \draw[dashed] (0,0) -- (0, 8) -- (2, 8);
      \draw (2, 8) -- (2, 0);
      \foreach \x in {0, 0.4, 1.2} {
        \draw[fill=mainColor!20] (\x, 0) rectangle ({\x+0.4}, {2*(\x+0.4)^2});
      }
      \node[below] at (0.4, 0) {$\frac{b}{n}$};
      \node[below] at (0.8, 0) {$\frac{2b}{n}$};
      \node[below] at (1.6, 0) {$\frac{kb}{n}$};
      \node[below right] at (2.0, 0) {$b = \frac{nb}{n}$};
      \draw[<->] (1.2, 5.3) -- ++(0.4, 0) node[midway, above] {$\frac{b}{n}$};
      \draw[<->] (1.7, 0) -- ++(0, 5.12) node[midway, right, fill=white, xshift=0.1cm] {$2\left(\frac{kb}{n}\right)^2$};
      \draw[-latex] (0.8, 6) node[above] {\small $A_k = 2 \dfrac{b^3}{n^3} k^2$} -- (1.2, 5.12); 
      \draw[mainColor, thick, domain=0:2, samples=50] plot (\x, {2*(\x)^2});
      \node at (1, -1.5) {(c) Por excesso};
    \end{scope}
    \end{tikzpicture}
    \end{figure}
    Consideremos um segmento parabólico da função $y = 2x^2$ no intervalo $[0, b]$. Dividimos esse intervalo em $n$ segmentos de comprimento $\dfrac{b}{n}$. Sobre tais segmentos, construímos retângulos inferiores à parábola. Assim, o $k-$ésimo segmento terá altura igual a $2\left(\dfrac{kb}{n}\right)^2$ e área :
    $$A_k = 2 \dfrac{b^3}{n^3}k^2$$
    em que $k = 1, 2, \cdots, n-1$. Dessa forma, somando todos os retãngulos inferiores, obtemos a aproximação por falta $s_n$ para a área do segmento parabólico:
    \begin{align*}
    s_n &= 2\dfrac{b^3}{n^3} \left[1^2 + 2^2 + 3^3 + \cdots + (n-1)^2\right]\\
    &= 2 \dfrac{b^3}{n^3} \left(\dfrac{n^3}{3} - \dfrac{n^2}{2} + \dfrac{n}{6}\right)\\
    &= \dfrac{2b^3}{3} - \dfrac{b^3}{n} + \dfrac{b^3}{3n^2}
    \end{align*}
    Analogamente, ao aproximar a área do segmento parabólico por retângulos exteriores, obtemos o seguinte somatório:
    \begin{align*}
    S_n &= 2\dfrac{b^3}{n^3} \left[1^2 + 2^2 + 3^3 + \cdots + (n-1)^2\right]\\
    &= 2 \dfrac{b^3}{n^3} \left(\dfrac{n^3}{3} - \dfrac{n^2}{2} + \dfrac{n}{6}\right)\\
    &= \dfrac{2b^3}{3} + \dfrac{b^3}{n} + \dfrac{b^3}{3n^2}
    \end{align*}
    Note-se que a desigualdade
    $$
    s_n < \dfrac{2b^3}{3} < S_n
    $$
    deve ser válida para cada valor de $n$, donde concluímos que a área do segmento parabólico $[0, b]$ da função $y = 2x^2$ deve ser $A = \dfrac{2b^3}{3}$.
  \end{enumerate}
  \fimSol
\end{enumerate}


\newpage

\begin{enumerate}
  \item \textbf{(FEI-SP)} Dois móveis $A$ e $B$, ambos com movimento uniforme, percorrem uma trajetória retilínea conforme mostra a figura. Em $t = 0$, estes se encontram, respectivamente, nos pontos $A$ e $B$ na trajetória. As velocidades dos móveis são $v_A = 50$ m/s e $v_B = 30$ m/s no mesmo sentido.
  
  \begin{figure}[H]
    \centering
    \begin{tikzpicture}
      \draw[-latex] (-0.5, 0) -- (8, 0);
      \foreach \i/\x/\y/\cor in {0/0/2/black, A/2/1.5/red, B/6/2/red}{
        \draw[dashed] (\x, 0) -- (\x, \y);
        \draw[\cor, thick] (\x, 0.1) -- (\x, -0.1) node[below, black] {$\i$};
      }
      \foreach \i/\x/\y in {50/2/1.5, 150/6/2}{
        \draw[latex-latex] (0, \y) -- (\x, \y) node[midway, above] {$\i$ m};
      }
    \end{tikzpicture}
  \end{figure}
  
  Em que instante a distância entre os dois móveis será 50 m?
  \begin{enumerate}[label=(\alph*)]
    \foreach \resp in {200, 225, 250, 300, 350} {
      \item $\resp$ m
    }
  \end{enumerate}
  
  \iniSol
  


  
  Escrevamos as equações horárias das trajétórias dos móveis $A$ e $B$, sabendo que ambos descrevem movimento uniforme:
  
  \begin{align*}
    \begin{cases}
      s_A = s_{0A} + v_A t\\
      s_B = s_{0B} + v_B t\\
    \end{cases}
  \end{align*}
  
  Os móveis encontram-se no instante $t^{*}$ tal que $s_A = s_B = s^{*}$, ou seja:
  \begin{align*}
    s_A = s_B &\Rightarrow s_{0A} + v_A t^{*} = s_{0B} + v_B t^{*}\\
    &\Rightarrow v_A t^{*} - v_B t^{*} = s_{0B} - s_{0A}\\
    &\Rightarrow (v_A  - v_B) t^{*} = s_{0B} - s_{0A}\\
    &\Rightarrow t^{*} = \dfrac{s_{0B} - s_{0A}}{v_A  - v_B}
  \end{align*}
  
  Nesse instante, a posição $s^{*}$ dos móveis será:
  
  \begin{align*}
    s^{*} = s_{0A} + v_A t^{*} \Rightarrow s^{*} = s_{0A} + v_A \left( \dfrac{s_{0B} - s_{0A}}{v_A  - v_B} \right)
  \end{align*}
  
  
  O script \verb|Python| abaixo mostra o resultano numérico correspondente ao desenvolvimento algébrico acima:
\end{enumerate}

```{python}
# Dados do problema
s_0A = 50
v_A = 50
s_0B = 150
v_B = 30

# Instante do encontro
t_star = (s_0B - s_0A) / (v_A - v_B)

# Posição do encontro
s_star = s_0A + v_A * t_star
```


  Os móveis encontram-se no instante $t^{*} = `r format(py$t_star, decimal.mark=",")`$ s e na posição $s^{*} = `r format(py$s_star, decimal.mark=",")`$ m.
  

  O gráfico abaixo mostra a posição de cada móvel em função do tempo, bem como o ponto de encontro.
  
```{python, include=FALSE}
import numpy as np
t = np.array([0, t_star, 1.5*t_star])
s_A = s_0A + v_A * t
s_B = s_0B + v_B * t

t_lim = [np.min(t)-t_star/3, np.max(t)+t_star/2]
s_lim = [-s_0A, np.max([np.max(s_A), np.max(s_B)]) + s_0A]
```

\begin{figure}[H]
  \centering
  \begin{tikzpicture}[x=0.5cm, y=0.01cm]
    % Eixo X
    \draw[-latex] (`r py$t_lim[1]`, 0) -- (`r py$t_lim[2]`, 0) node[below] {$t$ (s)};
    % Eixo Y
    \draw[-latex] (0, `r py$s_lim[1]`) -- (0, `r py$s_lim[2]`) node[left] {$s$ (m)};
    % Função Horária de A
    \draw[red, thick] (`r py$t[1]`, `r py$s_A[1]`) -- (`r py$t[3]`, `r py$s_A[3]`) node[right, yshift=5pt, black] {$\textbf{A}$};
    \draw[thick] (4pt, `r py$s_0A`) -- (-4pt, `r py$s_0A`) node[left] {$`r py$s_0A`$};
    % Função Horária de B
    \draw[mainColor, thick] (`r py$t[1]`, `r py$s_B[1]`) -- (`r py$t[3]`, `r py$s_B[3]`) node[right, yshift=-2pt , black] {$\textbf{B}$};
    \draw[thick] (4pt, `r py$s_0B`) -- (-4pt, `r py$s_0B`) node[left] {$`r py$s_0B`$};
    % Ponto de encontro
    \draw[dashed] (`r py$t_star`, 0) -- (`r py$t_star`, `r py$s_star`) -- (0, `r py$s_star`);
    \draw[thick] (`r py$t_star`, 4pt) -- (`r py$t_star`, -4pt) node[below] {$t^{*} = `r py$t_star`$};
    \draw[thick] (4pt, `r py$s_star`) -- (-4pt, `r py$s_star`) node[left] {$`r py$s_star`$};
  \end{tikzpicture}
\end{figure}



Portanto, a resposta correta é letra \textbf{D}.

\fimSol